---
name: Editorconfig linter

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: editorconfig-cli
        uses: editorconfig-checker/action-editorconfig-checker@v1.0.0
