---
name: Image optimization

on:
  push:
    branches: [main]
    paths:
      - '**.jpg'
      - '**.jpeg'
      - '**.png'
      - '**.webp'

  pull_request:
    branches: [main]
    paths:
      - '**.jpg'
      - '**.jpeg'
      - '**.png'
      - '**.webp'

jobs:
  optimize:
    name: calibreapp/image-actions
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Compress Images
        uses: calibreapp/image-actions@main
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
