---
name: Markdown linter

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: markdownlint-cli
        uses: tomtomsen/github-action-markdown-cli@v2.0.0
        with:
          files: .
