name: protected-files

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  protected-files:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Get changed files
        uses: lots0logs/gh-action-get-changed-files@2.1.4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Output
        run: |
          cat ${HOME}/files.json
          cat ${HOME}/files_modified.json
          cat ${HOME}/files_added.json
          cat ${HOME}/files_deleted.json
          cat ${HOME}/files_renamed.json
