---
name: Spelling check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Check Spelling (JS, Vue, HTML, Markdown, Text)
        uses: UnicornGlobal/spellcheck-github-actions@0.4.0
