---
name: YAML linter

on:
  push  :
    branches: [ main   ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  yaml-lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: yamllint
        uses: ibiqlik/action-yamllint@v3.0.1
        with:
          strict: true
